*! version 1.1  15apr2019
*! Minh Cong Nguyen, Raul Andres Castaneda Aguilar
! version 1.0  xxapr2016 - original code
! version 1.1  15apr2019 - add new country/group codes, except North Korea

cap program drop dlw_countryname 
program define dlw_countryname
	syntax, [savepath(string)]
qui {
	tempname n
	tempfile names
	postfile `n' str6 region str7 code str60 countryname using `names' , replace
	post `n' ("EAP") ("ASM") ("American Samoa")
	post `n' ("EAP") ("AUS") ("Australia")
	post `n' ("EAP") ("BRN") ("Brunei Darussalam")
	post `n' ("EAP") ("CHN") ("China")
	post `n' ("EAP") ("FJI") ("Fiji")
	post `n' ("EAP") ("FSM") ("Micronesia, Fed. Sts.")
	post `n' ("EAP") ("GUM") ("Guam")
	post `n' ("EAP") ("HKG") ("Hong Kong SAR, China")
	post `n' ("EAP") ("IDN") ("Indonesia")
	post `n' ("EAP") ("JPN") ("Japan")
	post `n' ("EAP") ("KHM") ("Cambodia")
	post `n' ("EAP") ("KIR") ("Kiribati")
	post `n' ("EAP") ("KOR") ("Korea, Rep.")
	post `n' ("EAP") ("LAO") ("Lao PDR")
	post `n' ("EAP") ("MAC") ("Macao SAR, China")
	post `n' ("EAP") ("MHL") ("Marshall Islands")
	post `n' ("EAP") ("MMR") ("Myanmar")
	post `n' ("EAP") ("MNG") ("Mongolia")
	post `n' ("EAP") ("MNP") ("Northern Mariana Islands")
	post `n' ("EAP") ("MYS") ("Malaysia")
	post `n' ("EAP") ("NCL") ("New Caledonia")
	post `n' ("EAP") ("NRU") ("Nauru")
	post `n' ("EAP") ("NZL") ("New Zealand")
	post `n' ("EAP") ("PHL") ("Philippines")
	post `n' ("EAP") ("PLW") ("Palau")
	post `n' ("EAP") ("PNG") ("Papua New Guinea")
*	post `n' ("EAP") ("PRK") ("Korea, Dem. People's Rep.")
	post `n' ("EAP") ("PYF") ("French Polynesia")
	post `n' ("EAP") ("SGP") ("Singapore")
	post `n' ("EAP") ("SLB") ("Solomon Islands")
	post `n' ("EAP") ("THA") ("Thailand")
	post `n' ("EAP") ("TLS") ("Timor-Leste")
	post `n' ("EAP") ("TON") ("Tonga")
	post `n' ("EAP") ("TUV") ("Tuvalu")
	post `n' ("EAP") ("TWN") ("Taiwan, China")
	post `n' ("EAP") ("VNM") ("Viet Nam")
	post `n' ("EAP") ("VUT") ("Vanuatu")
	post `n' ("EAP") ("WSM") ("Samoa")
*	post `n' ("EAP") ("EAP") ("East Asia & Pacific")
	post `n' ("ECA") ("ALB") ("Albania")
	post `n' ("ECA") ("AND") ("Andorra")
	post `n' ("ECA") ("ARM") ("Armenia")
	post `n' ("ECA") ("AUT") ("Austria")
	post `n' ("ECA") ("AZE") ("Azerbaijan")
	post `n' ("ECA") ("BEL") ("Belgium")
	post `n' ("ECA") ("BGR") ("Bulgaria")
	post `n' ("ECA") ("BIH") ("Bosnia and Herzegovina")
	post `n' ("ECA") ("BLR") ("Belarus")
	post `n' ("ECA") ("CHE") ("Switzerland")
	post `n' ("ECA") ("CHI") ("Channel Islands")
	post `n' ("ECA") ("CYP") ("Cyprus")
	post `n' ("ECA") ("CZE") ("Czech Republic")
	post `n' ("ECA") ("DEU") ("Germany")
	post `n' ("ECA") ("DNK") ("Denmark")
	post `n' ("ECA") ("ESP") ("Spain")
	post `n' ("ECA") ("EST") ("Estonia")
	post `n' ("ECA") ("FIN") ("Finland")
	post `n' ("ECA") ("FRA") ("France")
	post `n' ("ECA") ("FRO") ("Faroe Islands")
	post `n' ("ECA") ("GBR") ("United Kingdom")
	post `n' ("ECA") ("GEO") ("Georgia")
	post `n' ("ECA") ("GIB") ("Gibraltar")
	post `n' ("ECA") ("GRC") ("Greece")
	post `n' ("ECA") ("GRL") ("Greenland")
	post `n' ("ECA") ("HRV") ("Croatia")
	post `n' ("ECA") ("HUN") ("Hungary")
	post `n' ("ECA") ("IMN") ("Isle of Man")
	post `n' ("ECA") ("IRL") ("Ireland")
	post `n' ("ECA") ("ISL") ("Iceland")
	post `n' ("ECA") ("ITA") ("Italy")
	post `n' ("ECA") ("KAZ") ("Kazakhstan")
	post `n' ("ECA") ("KGZ") ("Kyrgyz Republic")
	post `n' ("ECA") ("XKX") ("Kosovo")
	post `n' ("ECA") ("LIE") ("Liechtenstein")
	post `n' ("ECA") ("LTU") ("Lithuania")
	post `n' ("ECA") ("LUX") ("Luxembourg")
	post `n' ("ECA") ("LVA") ("Latvia")
	post `n' ("ECA") ("MCO") ("Monaco")
	post `n' ("ECA") ("MDA") ("Moldova")
	post `n' ("ECA") ("MKD") ("North Macedonia")
	post `n' ("ECA") ("MNE") ("Montenegro")
	post `n' ("ECA") ("NLD") ("Netherlands")
	post `n' ("ECA") ("NOR") ("Norway")
	post `n' ("ECA") ("POL") ("Poland")
	post `n' ("ECA") ("PRT") ("Portugal")
	post `n' ("ECA") ("ROU") ("Romania")
	post `n' ("ECA") ("RUS") ("Russian Federation")
	post `n' ("ECA") ("SMR") ("San Marino")
	post `n' ("ECA") ("SRB") ("Serbia")
	post `n' ("ECA") ("SVK") ("Slovak Republic")
	post `n' ("ECA") ("SVN") ("Slovenia")
	post `n' ("ECA") ("SWE") ("Sweden")
	post `n' ("ECA") ("TJK") ("Tajikistan")
	post `n' ("ECA") ("TKM") ("Turkmenistan")
	post `n' ("ECA") ("TUR") ("Türkiye")
	post `n' ("ECA") ("UKR") ("Ukraine")
	post `n' ("ECA") ("UZB") ("Uzbekistan")
*	post `n' ("ECA") ("ECA") ("Europe & Central Asia")
	post `n' ("LAC") ("ABW") ("Aruba")
	post `n' ("LAC") ("ARG") ("Argentina")
	post `n' ("LAC") ("ATG") ("Antigua and Barbuda")
	post `n' ("LAC") ("BHS") ("Bahamas, The")
	post `n' ("LAC") ("BLZ") ("Belize")
	post `n' ("LAC") ("BOL") ("Bolivia")
	post `n' ("LAC") ("BRA") ("Brazil")
	post `n' ("LAC") ("BRB") ("Barbados")
	post `n' ("LAC") ("CHL") ("Chile")
	post `n' ("LAC") ("COL") ("Colombia")
	post `n' ("LAC") ("CRI") ("Costa Rica")
	post `n' ("LAC") ("CUB") ("Cuba")
	post `n' ("LAC") ("CUW") ("Curaçao")
	post `n' ("LAC") ("CYM") ("Cayman Islands")
	post `n' ("LAC") ("DMA") ("Dominica")
	post `n' ("LAC") ("DOM") ("Dominican Republic")
	post `n' ("LAC") ("ECU") ("Ecuador")
	post `n' ("LAC") ("GRD") ("Grenada")
	post `n' ("LAC") ("GTM") ("Guatemala")
	post `n' ("LAC") ("GUY") ("Guyana")
	post `n' ("LAC") ("HND") ("Honduras")
	post `n' ("LAC") ("HTI") ("Haiti")
	post `n' ("LAC") ("JAM") ("Jamaica")
	post `n' ("LAC") ("KNA") ("St. Kitts and Nevis")
	post `n' ("LAC") ("LCA") ("St. Lucia")
	post `n' ("LAC") ("MAF") ("St. Martin (French part)")
	post `n' ("LAC") ("MEX") ("Mexico")
	post `n' ("LAC") ("NIC") ("Nicaragua")
	post `n' ("LAC") ("PAN") ("Panama")
	post `n' ("LAC") ("PER") ("Peru")
	post `n' ("LAC") ("PRI") ("Puerto Rico")
	post `n' ("LAC") ("PRY") ("Paraguay")
	post `n' ("LAC") ("SLV") ("El Salvador")
	post `n' ("LAC") ("SUR") ("Suriname")
	post `n' ("LAC") ("SXM") ("Sint Maarten (Dutch part)")
	post `n' ("LAC") ("TCA") ("Turks and Caicos Islands")
	post `n' ("LAC") ("TTO") ("Trinidad and Tobago")
	post `n' ("LAC") ("URY") ("Uruguay")
	post `n' ("LAC") ("VCT") ("St. Vincent and the Grenadines")
	post `n' ("LAC") ("VEN") ("Venezuela, RB")
	post `n' ("LAC") ("VGB") ("British Virgin Islands")
	post `n' ("LAC") ("VIR") ("Virgin Islands (U.S.)")
*	post `n' ("LAC") ("LAC") ("Latin America & Caribbean")
	post `n' ("MNA") ("ARE") ("United Arab Emirates")
	post `n' ("MNA") ("BHR") ("Bahrain")
	post `n' ("MNA") ("DJI") ("Djibouti")
	post `n' ("MNA") ("DZA") ("Algeria")
	post `n' ("MNA") ("EGY") ("Egypt, Arab Rep.")
	post `n' ("MNA") ("IRN") ("Iran, Islamic Rep.")
	post `n' ("MNA") ("IRQ") ("Iraq")
	post `n' ("MNA") ("ISR") ("Israel")
	post `n' ("MNA") ("JOR") ("Jordan")
	post `n' ("MNA") ("KWT") ("Kuwait")
	post `n' ("MNA") ("LBN") ("Lebanon")
	post `n' ("MNA") ("LBY") ("Libya")
	post `n' ("MNA") ("MAR") ("Morocco")
	post `n' ("MNA") ("MLT") ("Malta")
	post `n' ("MNA") ("OMN") ("Oman")
	post `n' ("MNA") ("PSE") ("West Bank and Gaza")
	post `n' ("MNA") ("QAT") ("Qatar")
	post `n' ("MNA") ("SAU") ("Saudi Arabia")
	post `n' ("MNA") ("SYR") ("Syrian Arab Republic")
	post `n' ("MNA") ("TUN") ("Tunisia")
	post `n' ("MNA") ("YEM") ("Yemen, Rep.")
*	post `n' ("MNA") ("MNA") ("Middle East & North Africa")
	post `n' ("NAC") ("BMU") ("Bermuda")
	post `n' ("NAC") ("CAN") ("Canada")
	post `n' ("NAC") ("USA") ("United States")
*	post `n' ("NAC") ("NAC") ("North America")
	post `n' ("SAR") ("AFG") ("Afghanistan")
	post `n' ("SAR") ("BGD") ("Bangladesh")
	post `n' ("SAR") ("BTN") ("Bhutan")
	post `n' ("SAR") ("IND") ("India")
	post `n' ("SAR") ("LKA") ("Sri Lanka")
	post `n' ("SAR") ("MDV") ("Maldives")
	post `n' ("SAR") ("NPL") ("Nepal")
	post `n' ("SAR") ("PAK") ("Pakistan")
*	post `n' ("SAR") ("SAR") ("South Asia")
	post `n' ("SSA") ("AGO") ("Angola")
	post `n' ("SSA") ("BDI") ("Burundi")
	post `n' ("SSA") ("BEN") ("Benin")
	post `n' ("SSA") ("BFA") ("Burkina Faso")
	post `n' ("SSA") ("BWA") ("Botswana")
	post `n' ("SSA") ("CAF") ("Central African Republic")
	post `n' ("SSA") ("CIV") ("Côte dIvoire")
	post `n' ("SSA") ("CMR") ("Cameroon")
	post `n' ("SSA") ("COD") ("Congo, Dem. Rep.")
	post `n' ("SSA") ("COG") ("Congo, Rep.")
	post `n' ("SSA") ("COM") ("Comoros")
	post `n' ("SSA") ("CPV") ("Cabo Verde")
	post `n' ("SSA") ("ERI") ("Eritrea")
	post `n' ("SSA") ("ETH") ("Ethiopia")
	post `n' ("SSA") ("SWZ") ("Eswatini")
	post `n' ("SSA") ("GAB") ("Gabon")
	post `n' ("SSA") ("GHA") ("Ghana")
	post `n' ("SSA") ("GIN") ("Guinea")
	post `n' ("SSA") ("GMB") ("Gambia, The")
	post `n' ("SSA") ("GNB") ("Guinea-Bissau")
	post `n' ("SSA") ("GNQ") ("Equatorial Guinea")
	post `n' ("SSA") ("KEN") ("Kenya")
	post `n' ("SSA") ("LBR") ("Liberia")
	post `n' ("SSA") ("LSO") ("Lesotho")
	post `n' ("SSA") ("MDG") ("Madagascar")
	post `n' ("SSA") ("MLI") ("Mali")
	post `n' ("SSA") ("MOZ") ("Mozambique")
	post `n' ("SSA") ("MRT") ("Mauritania")
	post `n' ("SSA") ("MUS") ("Mauritius")
	post `n' ("SSA") ("MWI") ("Malawi")
	post `n' ("SSA") ("NAM") ("Namibia")
	post `n' ("SSA") ("NER") ("Niger")
	post `n' ("SSA") ("NGA") ("Nigeria")
	post `n' ("SSA") ("RWA") ("Rwanda")
	post `n' ("SSA") ("SDN") ("Sudan")
	post `n' ("SSA") ("SEN") ("Senegal")
	post `n' ("SSA") ("SLE") ("Sierra Leone")
	post `n' ("SSA") ("SOM") ("Somalia")
	post `n' ("SSA") ("SSD") ("South Sudan")
	post `n' ("SSA") ("STP") ("São Tomé and Principe")
	post `n' ("SSA") ("SYC") ("Seychelles")
	post `n' ("SSA") ("TCD") ("Chad")
	post `n' ("SSA") ("TGO") ("Togo")
	post `n' ("SSA") ("TZA") ("Tanzania")
	post `n' ("SSA") ("UGA") ("Uganda")
	post `n' ("SSA") ("ZAF") ("South Africa")
	post `n' ("SSA") ("ZMB") ("Zambia")
	post `n' ("SSA") ("ZWE") ("Zimbabwe")
*	post `n' ("SSA") ("SSA") ("Sub-Saharan Africa")
	
	post `n' ("OTHERS") ("SUPPORT") ("Support")
	post `n' ("OTHERS") ("WLD") ("World")
	post `n' ("OTHERS") ("EAP") ("East Asia & Pacific (excluding high income)")
	post `n' ("OTHERS") ("ECA") ("Europe & Central Asia (excluding high income)")
	post `n' ("OTHERS") ("LAC") ("Latin America & Caribbean (excluding high income)")
	post `n' ("OTHERS") ("MNA") ("Middle East & North Africa (excluding high income)")
	post `n' ("OTHERS") ("NAC") ("North America")
	post `n' ("OTHERS") ("SAR") ("South Asia")
	post `n' ("OTHERS") ("SSA") ("Sub-Saharan Africa (excluding high income)")
	post `n' ("OTHERS") ("ARB") ("Arab World")
	post `n' ("OTHERS") ("CSS") ("Caribbean small states")
	post `n' ("OTHERS") ("CEB") ("Central Europe and the Baltics")
	post `n' ("OTHERS") ("EAR") ("Early-demographic dividend")
	post `n' ("OTHERS") ("EAS") ("East Asia & Pacific")
	post `n' ("OTHERS") ("TEA") ("East Asia & Pacific (IDA & IBRD)")
	post `n' ("OTHERS") ("EMU") ("Euro area")
	post `n' ("OTHERS") ("ECS") ("Europe & Central Asia")
	post `n' ("OTHERS") ("TEC") ("Europe & Central Asia (IDA & IBRD)")
	post `n' ("OTHERS") ("EUU") ("European Union")
	post `n' ("OTHERS") ("FCS") ("Fragile and conflict affected situations")
	post `n' ("OTHERS") ("HPC") ("Heavily indebted poor countries (HIPC)")
	post `n' ("OTHERS") ("HIC") ("High income")
	post `n' ("OTHERS") ("IBD") ("IBRD only")
	post `n' ("OTHERS") ("IBT") ("IDA & IBRD total")
	post `n' ("OTHERS") ("IDB") ("IDA blend")
	post `n' ("OTHERS") ("IDX") ("IDA only")
	post `n' ("OTHERS") ("IDA") ("IDA total")
	post `n' ("OTHERS") ("LTE") ("Late-demographic dividend")
	post `n' ("OTHERS") ("LCN") ("Latin America & Caribbean")
	post `n' ("OTHERS") ("TLA") ("Latin America & Caribbean (IDA & IBRD)")
	post `n' ("OTHERS") ("LDC") ("Least developed countries: UN classification")
	post `n' ("OTHERS") ("LMY") ("Low & middle income")
	post `n' ("OTHERS") ("LIC") ("Low income")
	post `n' ("OTHERS") ("LMC") ("Lower middle income")
	post `n' ("OTHERS") ("MEA") ("Middle East & North Africa")
	post `n' ("OTHERS") ("TMN") ("Middle East & North Africa (IDA & IBRD)")
	post `n' ("OTHERS") ("MIC") ("Middle income")
	post `n' ("OTHERS") ("OED") ("OECD members")
	post `n' ("OTHERS") ("OSS") ("Other small states")
	post `n' ("OTHERS") ("PSS") ("Pacific island small states")
	post `n' ("OTHERS") ("PST") ("Post-demographic dividend")
	post `n' ("OTHERS") ("PRE") ("Pre-demographic dividend")
	post `n' ("OTHERS") ("SST") ("Small states")
	post `n' ("OTHERS") ("TSA") ("South Asia (IDA & IBRD)")
	post `n' ("OTHERS") ("SSF") ("Sub-Saharan Africa")
	post `n' ("OTHERS") ("TSS") ("Sub-Saharan Africa (IDA & IBRD)")
	post `n' ("OTHERS") ("UMC") ("Upper middle income")

	postclose `n'
	if "`savepath'"=="" {
		use `names', clear 
		ren code countrycode 
		label var region "Region"
		label var countrycode "Country Code"
		label var countryname "Country Name"
		compress
	}
	else {		
		copy "`names'" "`savepath'", replace
	}
}
end
